### PR TITLE
Update accounts_pool.py

### PR DESCRIPTION
**Pull request by variousred**
update ON CONFLICT query

### CODE REVIEW

**Comment by variousred** [comment]
looks like this was added in 3.35, and python is shipping with 3.34

**Comment by variousred** [comment]
actually cant find any python with the latest sqlite3. Having to start from a base alpine image and install sqlite3 and then compiling python with it

**Comment by vladkens** [comment]
Hi, @variousred. Thank you.

I have a newer version installed locally, so I didn't notice it. And in my dockerfile I have something like that:

```dockerfile
FROM python:3.11-alpine
RUN apk update && apk upgrade
RUN apk add --no-cache build-base libffi-dev git sqlite
```

I will add a sqlite version check to the code in the upcoming release (I have some fixes for working with DB in principle)

**Comment by variousred** [comment]
Thanks vladkens!

**Comment by variousred** [comment]
note: that on conflict wasnt the only newer syntax. cant remember the other , will look

**Comment by variousred** [comment]
@vladkens 
```
    async def get_for_queue(self, queue: str):
        q1 = f"""
        SELECT username FROM accounts
        WHERE active = true AND (
            locks IS NULL
         OR json_extract(locks, '$.{queue}') IS NULL
            OR json_extract(locks, '$.{queue}') < datetime('now')
        )
        ORDER BY RANDOM()
        LIMIT 1
        """

        # Get the username from the first query
        username_rs = await fetchone(self._db_file, q1)
        if username_rs:
            username = username_rs["username"]

            q2 = f"""
            UPDATE accounts SET locks = json_set(locks, '$.{queue}', datetime('now', '+15 minutes'))
            WHERE username = ?
            """

            # Execute the second query to update the accounts table
            await execute(self._db_file, q2, (username,))

            q3 = f"""
            SELECT * FROM accounts
            WHERE username = ?
            """

            # Execute the third query to fetch the updated account
            rs = await fetchone(self._db_file, q3, (username,))
            return Account.from_rs(rs) if rs else None
        else:
            return None
            
```
this is the update for the RETURNING problem

**Comment by variousred** [comment]
@vladkens ☝🏻

**Comment by variousred** [comment]
made a PR for it
https://github.com/vladkens/twscrape/pull/10

**Pull request merged**
